<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxgmhb8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxgmhb8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOxgmhb8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOxgmhb8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOxgmhb8\appDevDebugProjectContainer([
    'container.build_hash' => 'Oxgmhb8',
    'container.build_id' => 'e2680c5f',
    'container.build_time' => 1559226675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxgmhb8');
