<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIk2jvds\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIk2jvds/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIk2jvds.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIk2jvds\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIk2jvds\appDevDebugProjectContainer([
    'container.build_hash' => 'Ik2jvds',
    'container.build_id' => 'af4295b9',
    'container.build_time' => 1559214787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIk2jvds');
